buildOTF: false
buildSmallCap: false
buildStatic: false
buildTTF: false
buildVariable: true
buildWebfont: false
familyName: Sudo
sources:
- Sudo.glyphspackage
recipeProvider: googlefonts
recipe:
  ../fonts/variable/Sudo-Italic[YTDE,wght].ttf:
  - source: Sudo.glyphspackage
  - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildVariable
  - axes: ital=1
    operation: subspace
  - args: -o $out $in fontsetter/Sudo-Italic.fontsetter
    exe: gftools-fontsetter
    operation: exec
  - args: --include-source-fixes
    operation: fix
  - args: -f ital
    operation: featureFreeze
  - args: --layout-features-=ss04 --layout-features-=kern
    operation: hbsubset
  - args: --src stat.yaml
    needs:
    - ../fonts/variable/Sudo[YTDE,wght].ttf
    postprocess: buildStat

  ../fonts/variable/Sudo[YTDE,wght].ttf:
  - source: Sudo.glyphspackage
  - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildVariable
  - axes: ital=0
    operation: subspace
  - args: -o $out $in fontsetter/Sudo.fontsetter
    exe: gftools-fontsetter
    operation: exec
  - operation: fix
  - args: --layout-features-=ss04 --layout-features-=kern --layout-features-=ital
    operation: hbsubset

  ../fonts/variable/SudoUI-Italic[YTDE,wght].ttf:
  - source: Sudo.glyphspackage
  - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildVariable
  - axes: ital=1
    operation: subspace
  - name: "Sudo UI"
    operation: rename
  - args: -o $out $in fontsetter/SudoUI-Italic.fontsetter
    exe: gftools-fontsetter
    operation: exec
  - args: --include-source-fixes
    operation: fix
  - args: -f zero,ss20,ital
    operation: featureFreeze
  - operation: hbsubset
  - args: --src stat.yaml
    needs:
    - ../fonts/variable/SudoUI[YTDE,wght].ttf
    postprocess: buildStat

  ../fonts/variable/SudoUI[YTDE,wght].ttf:
  - source: Sudo.glyphspackage
  - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildVariable
  - axes: ital=0
    operation: subspace
  - name: "Sudo UI"
    operation: rename
  - args: -o $out $in fontsetter/SudoUI.fontsetter
    exe: gftools-fontsetter
    operation: exec
  - operation: fix
  - args: -f zero,ss20
    operation: featureFreeze
  - args: --layout-features-=ital
    operation: hbsubset
