buildOTF: false
buildSmallCap: false
buildStatic: false
buildTTF: false
buildVariable: true
buildWebfont: false
familyName: Sudo
sources:
- Sudo.glyphspackage
recipeProvider: googlefonts
recipe:
  ../fonts/variable/Sudo-Italic[YTDE,wght].ttf:
  - source: Sudo.glyphspackage
  - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildVariable
  - axes: ital=1
    operation: subspace
  - args: --include-source-fixes
    operation: fix
  - args: ''
    operation: fix
  - args: -o $out $in fontsetter/Sudo-Italic.fontsetter
    exe: gftools-fontsetter
    operation: exec
  - args: "!ss04 !kern 'ital=>rclt'"
    operation: remapLayout
  - args: --src stat.yaml
    needs:
    - ../fonts/variable/Sudo[YTDE,wght].ttf
    postprocess: buildStat

  ../fonts/variable/Sudo[YTDE,wght].ttf:
  - source: Sudo.glyphspackage
  - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildVariable
  - axes: ital=0
    operation: subspace
  - args: ''
    operation: fix
  - args: -o $out $in fontsetter/Sudo.fontsetter
    exe: gftools-fontsetter
    operation: exec
  - args: "!ss04 !kern !ital"
    operation: remapLayout

  ../fonts/variable/SudoUI-Italic[YTDE,wght].ttf:
  - source: Sudo.glyphspackage
  - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildVariable
  - axes: ital=1
    operation: subspace
  - args: --include-source-fixes
    operation: fix
  - args: ''
    operation: fix
  - args: ''
    name: "Sudo UI"
    operation: rename
  - args: -o $out $in fontsetter/SudoUI-Italic.fontsetter
    exe: gftools-fontsetter
    operation: exec
  - args: "'zero=>rclt' 'ss20=>rclt' 'ital=>rclt'"
    operation: remapLayout
  - args: --src stat.yaml
    needs:
    - ../fonts/variable/SudoUI[YTDE,wght].ttf
    postprocess: buildStat

  ../fonts/variable/SudoUI[YTDE,wght].ttf:
  - source: Sudo.glyphspackage
  - args: --filter ...  --filter FlattenComponentsFilter --filter DecomposeTransformedComponentsFilter
    operation: buildVariable
  - axes: ital=0
    operation: subspace
  - args: ''
    operation: fix
  - args: ''
    name: "Sudo UI"
    operation: rename
  - args: -o $out $in fontsetter/SudoUI.fontsetter
    exe: gftools-fontsetter
    operation: exec
  - args: "'zero=>rclt' 'ss20=>rclt' !ital"
    operation: remapLayout
